### ISSUE TITLE
Defensive instinct shifter bug

### ISSUE THREAD

**Issue by qazcdewsx** [ScaredKurufinve/Way-of-the-shield#22]
Whilst wearing no armour you do not get any bonus to ac from Defensive instinct. You do get the half bonus when you are wearing non metal armour. You also don't get the Defensive instincts ac bonus when you've shifted into your major form. 

If you load a character that wasn't previously using way of the shield and add it then defensive instinct seems to function correctly when the character is unarmoured. However the ac bonus you get whilst wearing armour does not get reduced. Instead you keep the full bonus from your wisdom modifier and get two extra sets of ac from defensive instinct based, one of which scales based on your shifter level and the other which seems locked at +2 ac.

This lasts until you equip a shield at which point it changes to the behaviour mentioned at the beginning and stays that way even when the shield is unequipped.

I switched off all my mods other than toybox to test all of this.

Also another issue that might be related is that monks don't get any of there ac bonus, there extra movement or flurry of blows despite not being encumbered or wearing any armour.

**Comment by ScaredKurufinve** [comment]
Thank you very much for the deailed report. My attention has already been brought to it on Discord yesterday, but I did not have enough free time to look into it. Apparently some changes to the Unhindering Shield made it so that all relevant abilitis inluding Shifter AC bonus and Magus Spell Combat do not work without it <_< Unfortunately, there seems to be a much more severe bug related to it when one of TabletopTweaks-Base options is enabled; this may require couple more days to figure out.

**Comment by qazcdewsx** [comment]
It seems shifters defensive instinct is now giving the correct amount of ac when armour is and isn't being worn. Also monk seems to be getting its unarmoured bonuses as well. Since your discord message with the fix also mentioned spell combat I checked that quickly it seems to be working. 
I didn't look at the inventory and looting bugs mentioned in the message because I'm not sure what those are.
