### ISSUE TITLE
Character sheet blank

### ISSUE THREAD

**Issue by gabrielarantest** [ScaredKurufinve/Way-of-the-shield#23]
First of all, great mod love it. Particularly the closer to tabletop rules such as flaking and soft cover. Thank you for making this.

Now, I found a bug where if I activate an option such as to allow character to wear a buckler with a two-handed weapon, and later regret and turn this option off, when I load the game with this option off the UI will basically break. You can't select members of the party properly and most of the tabs in their sheet are blank such as "abilities" or "Martial" tabs.

Another thing that I would like to request, if you allow me, is to include the option to hide the buckler or change its position in the character's arms. I ask this because the position of the buckler while holding a two-handed weapon is really wierd.

**Comment by ScaredKurufinve** [comment]
Can you send me the GameLogFull? I'm ubale to reproduce this bug on my own.

I would be glad to fix the shield position when wielding 2-handedly, but that's rather difficult. I may see to add the option to hide it.

**Comment by gabrielarantest** [comment]
How do I send you the GameLogFull?

**Comment by ScaredKurufinve** [comment]
No, it lies in the folder where your saved games are located. If you are on Windows, that would be `%UserProfile%\AppData\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous`

**Comment by gabrielarantest** [comment]
Here are all my logs and a picture of what is going on: https://drive.google.com/drive/folders/1dFq8v96gFXcF4xzOACL3apIvyGQvJ_o9?usp=sharing

I hope it helps

**Comment by ScaredKurufinve** [comment]
It helped 👍 I'll get to fix it when I come back from work.

**Comment by gabrielarantest** [comment]
Oh so you figured it out? Thats great! Thanks!

**Comment by ScaredKurufinve** [comment]
Try out  the dll from this archive (copy it into the mod's Assemblies folder instead of the one that's already there).
[Way of the shield.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11233050/Way.of.the.shield.zip)
If the problem remains, send me the new log - that would mean there's another error hiding behind the one I fixed.

On a totally unrelated note... if it's not too much, may I ask you to test out the Bastion of Good ability of the Sacred Shield paladin (the archtype provided by this mod). It works perfectly fine on my machine, but people say it does not for them. I'd like to know if it works for _anybody_ other than me. It's basically the a usual smite, but the target should deal only halved damage to paladin's nearby allies (assuming the smiten creature is evil). If the ability is working, the damage breakdown will have an additional `(x 0.5)` multiplier.

**Comment by gabrielarantest** [comment]
Hi, thank you for fixing this. It seems to be working now! Are you going to publish this update? Any plans on the invisible buckler?

I tested the bastion of god. Indeed, it is only working partially for me. The bonus to the AC for the paladin is working, however, the halved damage is not, in case you want to see some screenshots: https://drive.google.com/drive/folders/1vDKq3y00D3wT9XQ04TVsCVk4WMUevdai?usp=sharing

**Comment by ScaredKurufinve** [comment]
I'd like to solve the mystery with the Bastion before I make a publish an update. Anyway, it should come in a couple of days if I can't figure out the deal...
I do have plans on hiding the buckler, but this is no a critical issue, so I'd first prefer to see how viable it is try and fix the attach point for it. I was looking through the code yesterday and somehow can't find the place where it is attached to the hand bone.

Thank you for your cooperation :)

**Comment by ScaredKurufinve** [comment]
Small preview
![5](https://user-images.githubusercontent.com/126824833/232338023-23528a59-850b-472f-97a6-95c182b24f7b.jpg)
![6](https://user-images.githubusercontent.com/126824833/232338024-514f7586-1879-45e9-b9b1-7488c968999f.jpg)
![7](https://user-images.githubusercontent.com/126824833/232338025-c59d81ef-69b7-49e5-88e4-82c004059a2c.jpg)
![9](https://user-images.githubusercontent.com/126824833/232338026-4acc730b-d3cd-412c-b6a3-f1b5a9334a16.jpg)
![10](https://user-images.githubusercontent.com/126824833/232338027-36b96ef4-b88f-472d-b182-d3a448716825.jpg)

**Comment by gabrielarantest** [comment]
Wow!! Great job! Amazing!!
