### ISSUE TITLE
[Not proficient with this weapon]

### ISSUE THREAD

**Issue by vinince** [ScaredKurufinve/Way-of-the-shield#27]
Hi.

Whenever I try to use the Shield Bash feat I'm getting an extra penalty " -4 [Not proficient with this weapon] " with the shield (light or heavy) on the left hand attack. Is this normal?

Thanks.

**Comment by ScaredKurufinve** [comment]
Hm, no. This is not normal. What gives you profficiency wit shields? The usual "Shields Profficiency" feat?

**Comment by vinince** [comment]
Yes, the default one that gives Buckler, Light and Heavy shields. Tried on a Ranger and a Paladin, same issue. It's like I'm not proficient only when I activate the Shield Bash, otherwise it's fine.

**Comment by ScaredKurufinve** [comment]
Hm, can you please take the DLL file from the mod's Debug folder and place it instead of the existing one in the Assemblies folder (you'll probably want to switch them back later, so maybe back up the existing one). Launch the game and send me your GameLogFull. It's possible that one of mod setting prevents from adding the proficiency to the feat, but I don't see a problem from the get-go.

> It's like I'm not proficient only when I activate the Shield Bash, otherwise it's fine.

That's because a shield is internally two different items - a weapon and an armor. Ability to equip the shield comes from the armor proficiency and by default it does not provide proficiency with the weapon part.

**Comment by vinince** [comment]
[GameLogFull.txt](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11646512/GameLogFull.txt)

**Comment by ScaredKurufinve** [comment]
Try the one from the archive. Should fix the issue if I'm not missing something.
[Way of the shield.zip](https://github.com/ScaredKurufinve/Way-of-the-shield/files/11646543/Way.of.the.shield.zip)

**Comment by vinince** [comment]
Yes! That bad penalty is gone now. Many thanks!

**Comment by ScaredKurufinve** [comment]
Thank you for the bug report too :)
