### ISSUE TITLE
a confict between parry abilities & duplicate icons

### ISSUE THREAD

**Issue by nixgnot** [ScaredKurufinve/Way-of-the-shield#3]
1 while i use the Parry(vanilla duelist ) TOGETHER with buckler parry, it will happend.
usually buckler parry will give me a "count" buff, and it will auto removed at the start of my next turn.
but if i have Parry actived,  the "count" buff will NOT removed at the start of my next turn.
and this means i "lose" my offhand buckler so that i cant use buckler shield bash(with upsetting) in this turn.

2 looks like i will have some duplicate icons if i have more than one class(they have same guid).

![1](https://user-images.githubusercontent.com/20860979/222906790-3df9e2e0-0cfc-480d-bdcf-251741a37946.png)
![2](https://user-images.githubusercontent.com/20860979/222908215-7275f754-9d82-4f06-842a-33bbe869baa3.png)

**Comment by ScaredKurufinve** [comment]
The parry problem is unexpected, because my parry has nothing to do with Duelist Parry and I would not expect any inteaction. I will look into that.
With regards to duplicated abilities - are you able to reproduce the bug more reliably? I did encounter it several times, but simply taking another lvl dip doesn't seem to cause it for me.

**Comment by nixgnot** [comment]
> are you able to reproduce the bug more reliably?

looks like use a backgroud which provide buckler Proficiency is very likely cause this happend.

**Comment by ScaredKurufinve** [comment]
That's nice to know. I'll try to figure out what is wrong with it later today.
The parry problem may be slightly more fundamental though. The counter buff is in fact the icon of the activated toggle ability which is set to activate on attack and deactivate after the first turn (with a default OwlCat mechanics). If it doesn't deactivate, there's something wrong. (It may also possibly mean that only the icon remains, but not the buff itself.)

**Comment by nixgnot** [comment]
> If it doesn't deactivate, there's something wrong. (It may also possibly mean that only the icon remains, but not the buff itself.)
not sure... but as above...the problem is, while i see that icon, i cant use my offhand shield attacks in this turn...i can only have main hand (weapon) attacks. its boring.
it will not happend while i dont active vanilla  parry
(btw, if this be fixed,  a double parry build will be really COOL :P)

**Comment by ScaredKurufinve** [comment]
O-o-oh. I think I know what's going on here. There indeed was a bad interaction between Duelist Parry and Buckler Parry which  I found thanks to you (so you will be able to have double parry when I publish next release even though I don't like such builds), but the problem you described most likely lies in having 2 copies of the Buckler parry. However the point here is - you are not supposed to be able to bash while using new abilities - this is deliberate by design, sorry. It was actually possible when I coded it first and I saw this loophole only just before the release and forgot to update the description. In the worst case you may fork the repo and re-build it yourself after deleting the `if (flag is false && !OffHandParryUnitPart.flag) return flag;` line in the `OffHandParry.BucklerOrBash(bool flag, RuleCalculateAttacksCount evt)` method.
